//
//  Class.swift
//  AirBnbProject
//
//  Created by Rachit Sharma on 23/07/2025.
//

import Foundation
class ListingDataService {
    var listings: [Listing] = [ Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "John Smith",
        ownerImageUrl: "hotel - men",
        numberOfBedrooms: 4,
        numberOfBathrooms: 3,
        numberOfGuests: 8,
        numberOfBeds: 5,
        pricePerNight: 500,
        latitude: 25.7617,
        longitude: -80.1918,
        address: "124 Palm Avenue",
        images: ["hotel - 1","hotel - 2","hotel - 3"],
        city: "Miami",
        state: "Florida",
        title: "Luxury Villa with Ocean View",
        rating: 4.86,
        type: .villa,
        fetures: [.selfCheakIn, .SuperHost],
        amenities: [.balcony, .kitchen, .pool, .wifi, .tv, .laundry, .alarmSystem]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Sarah Johnson",
        ownerImageUrl: "hotel - p - 1",
        numberOfBedrooms: 2,
        numberOfBathrooms: 2,
        numberOfGuests: 4,
        numberOfBeds: 2,
        pricePerNight: 350,
        latitude: 40.7128,
        longitude: -74.0060,
        address: "567 Broadway",
        images: ["hotel - 4","hotel - 5","hotel - 6"],
        city: " NewYork",
        state: "New York",
        title: "Modern Manhattan Apartment",
        rating: 4.92,
        type: .apartment,
        fetures: [.SuperHost],
        amenities: [.wifi, .tv, .kitchen, .alarmSystem, .office]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Michael Rodriguez",
        ownerImageUrl: "hotel - p - 2",
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        numberOfGuests: 6,
        numberOfBeds: 3,
        pricePerNight: 425,
        latitude: 32.7157,
        longitude: -117.1611,
        address: "789 Oceanfront Drive",
        images: ["hotel - 7","hotel - 8","hotel - 9"],
        city: "San Diego",
        state: "California",
        title: "Beachfront Condo with Stunning Views",
        rating: 4.78,
        type: .condo,
        fetures: [.selfCheakIn, .SuperHost],
        amenities: [.balcony, .pool, .wifi, .tv, .kitchen, .laundry]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Emily Wilson",
        ownerImageUrl: "hotel - p - 3",
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        numberOfGuests: 5,
        numberOfBeds: 3,
        pricePerNight: 275,
        latitude: 41.8781,
        longitude: -87.6298,
        address: "432 Wacker Drive",
        images: ["hotel - 10","hotel - 4","hotel - 2"],
        city: "Chicago",
        state: "Illinois",
        title: "Cozy Townhouse in Downtown Chicago",
        rating: 4.65,
        type: .townhouse,
        fetures: [.selfCheakIn],
        amenities: [.wifi, .tv, .kitchen, .office, .laundry]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "David Chen",
        ownerImageUrl: "hotel - p - 4",
        numberOfBedrooms: 4,
        numberOfBathrooms: 3,
        numberOfGuests: 8,
        numberOfBeds: 6,
        pricePerNight: 390,
        latitude: 39.7392,
        longitude: -104.9903,
        address: "1024 Mountain View Road",
        images: ["hotel - 6","hotel - 5","hotel - 3"],
        city: "Denver",
        state: "Colorado",
        title: "Mountain House with Scenic Views",
        rating: 4.89,
        type: .house,
        fetures: [.SuperHost],
        amenities: [.balcony, .wifi, .tv, .kitchen, .laundry, .office, .alarmSystem]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Jessica Taylor",
        ownerImageUrl: "hotel - p - 5",
        numberOfBedrooms: 2,
        numberOfBathrooms: 2,
        numberOfGuests: 4,
        numberOfBeds: 2,
        pricePerNight: 375,
        latitude: 34.0522,
        longitude: -118.2437,
        address: "888 Sunset Boulevard",
        images: ["hotel - 4","hotel - 2","hotel - 1"],
        city: "Los Angeles",
        state: "California",
        title: "Luxury Apartment in Hollywood Hills",
        rating: 4.95,
        type: .apartment,
        fetures: [.selfCheakIn, .SuperHost],
        amenities: [.balcony, .pool, .wifi, .tv, .kitchen, .laundry, .alarmSystem]
    ),
    
    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Robert Williams",
        ownerImageUrl: "hotel - p - 6",
        numberOfBedrooms: 3,
        numberOfBathrooms: 2,
        numberOfGuests: 6,
        numberOfBeds: 4,
        pricePerNight: 320,
        latitude: 42.3601,
        longitude: -71.0589,
        address: "45 Beacon Street",
        images: ["hotel - 5","hotel - 3"],
        city: "Boston",
        state: "Massachusetts",
        title: "Historic Townhouse in Beacon Hill",
        rating: 4.82,
        type: .townhouse,
        fetures: [.SuperHost],
        amenities: [.wifi, .tv, .kitchen, .office, .laundry]
    ),

    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Amanda Lopez",
        ownerImageUrl: "hotel - p - 7",
        numberOfBedrooms: 5,
        numberOfBathrooms: 4,
        numberOfGuests: 10,
        numberOfBeds: 7,
        pricePerNight: 550,
        latitude: 30.2672,
        longitude: -97.7431,
        address: "321 Lakeside Drive",
        images: ["hotel - 8","hotel - 9","hotel - 10"],
        city: "Austin",
        state: "Texas",
        title: "Lakefront Villa with Private Dock",
        rating: 4.91,
        type: .villa,
        fetures: [.selfCheakIn, .SuperHost],
        amenities: [.balcony, .pool, .wifi, .tv, .kitchen, .laundry, .office, .alarmSystem]
    ),

    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Daniel Kim",
        ownerImageUrl: "hotel - p - 10",
        numberOfBedrooms: 2,
        numberOfBathrooms: 2,
        numberOfGuests: 4,
        numberOfBeds: 2,
        pricePerNight: 290,
        latitude: 47.6062,
        longitude: -122.3321,
        address: "555 Pike Street",
        images: ["hotel - 3","hotel - 2","hotel - 9"],
        city: "Seattle",
        state: "Washington",
        title: "Modern Condo with Space Needle View",
        rating: 4.84,
        type: .condo,
        fetures: [.selfCheakIn],
        amenities: [.balcony, .wifi, .tv, .kitchen, .laundry, .office]
    ),
    

    Listing(
        id: UUID(),
        ownerUid: UUID(),
        ownerName: "Lisa Nakamura",
        ownerImageUrl: "hotel - p - 10",
        numberOfBedrooms: 4,
        numberOfBathrooms: 3,
        numberOfGuests: 8,
        numberOfBeds: 5,
        pricePerNight: 625,
        latitude: 21.3069,
        longitude: -157.8583,
        address: "123 Waikiki Beach Road",
        images: ["hotel - 7","hotel - 2","hotel - 9"],
        city: "Honolulu",
        state: "Hawaii",
        title: "Beachfront House with Private Access",
        rating: 4.97,
        type: .house,
        fetures: [.SuperHost],
        amenities: [.balcony, .pool, .wifi, .tv, .kitchen, .laundry, .alarmSystem]
    )]
    
}
